chat:
  chat-symbol: '»'
  groups:
    cherry:
      prefix: "&d&lCHERRY &r&8|"
    bamboo:
      prefix: "&a&lBAMBOO &r&8|"
    flower:
      prefix: "&e&lFLOWER &r&8|"
    frost:
      prefix: "&b&lFROST &r&8|"
    jungle:
      prefix: "&2&lJUNGLE &r&8|"