name: SMPChatPlugin
version: '${version}'
main: de.kenseiclan.mc.smpchatplugin.SMPChatPlugin
api-version: '1.20'
permissions:
  chat.*:
    default: false
    children:
      chatgroup.*:
        description: defines the group
        default: false